apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../base/cluster-name-secret/
- ../../base/bitnami-charts
- ../../base/cert-manager
