---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 10m0s
  path: flux/apps/clusters/${cluster_name}
  prune: true
  postBuild:
    substitute:
      cluster_name: ${cluster_name}
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: infra-gitops